# Generated by Django 3.1.7 on 2021-02-19 19:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodels',
            old_name='tagline',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='blog',
        ),
        migrations.AlterField(
            model_name='categorymodels',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='content', unique=True),
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
    ]
