# Generated by Django 3.1.7 on 2021-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0002_auto_20210219_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodels',
            name='slug',
        ),
    ]
