# Generated by Django 3.1.7 on 2021-02-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0003_remove_categorymodels_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodels',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
