# Generated by Django 3.1.7 on 2021-02-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0004_auto_20210219_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='makale', to='blog_application.CategoryModels'),
        ),
    ]
